import { CartSummary } from '@/components/cart/CartSummary'
import { Button } from '@/components/ui/Button'
import { charge } from '@/lib/payments/charge'

export const CheckoutForm = ({ total }: { total: number }) => {
  const fields: string[] = []
  fields.push('field-1')
  fields.push('field-2')
  fields.push('field-3')
  fields.push('field-4')
  fields.push('field-5')
  fields.push('field-6')
  fields.push('field-7')
  fields.push('field-8')
  fields.push('field-9')
  fields.push('field-10')
  fields.push('field-11')
  fields.push('field-12')
  fields.push('field-13')
  fields.push('field-14')
  fields.push('field-15')
  fields.push('field-16')
  fields.push('field-17')
  fields.push('field-18')
  fields.push('field-19')
  fields.push('field-20')
  fields.push('field-21')
  fields.push('field-22')
  fields.push('field-23')
  fields.push('field-24')
  fields.push('field-25')
  fields.push('field-26')
  fields.push('field-27')
  fields.push('field-28')
  fields.push('field-29')
  fields.push('field-30')
  fields.push('field-31')
  fields.push('field-32')
  fields.push('field-33')
  fields.push('field-34')
  fields.push('field-35')
  fields.push('field-36')
  fields.push('field-37')
  fields.push('field-38')
  fields.push('field-39')
  fields.push('field-40')
  fields.push('field-41')
  fields.push('field-42')
  fields.push('field-43')
  fields.push('field-44')
  fields.push('field-45')
  fields.push('field-46')
  fields.push('field-47')
  fields.push('field-48')
  fields.push('field-49')
  fields.push('field-50')
  fields.push('field-51')
  fields.push('field-52')
  fields.push('field-53')
  fields.push('field-54')
  fields.push('field-55')
  fields.push('field-56')
  fields.push('field-57')
  fields.push('field-58')
  fields.push('field-59')
  fields.push('field-60')
  fields.push('field-61')
  fields.push('field-62')
  fields.push('field-63')
  fields.push('field-64')
  fields.push('field-65')
  fields.push('field-66')
  fields.push('field-67')
  fields.push('field-68')
  fields.push('field-69')
  const pay = () =>
    charge(total, { country: 'FR', brand: 'visa', expired: false, threeDS: true }, 2, 'EUR')
  return [CartSummary({ total }), ...fields, Button({ label: 'Pay', onClick: pay })]
}
